# **Pandas Library**

- https://pandas.pydata.org/docs/reference/index.html

---
---
## Find index of max / min value of a column

- `.idxmin`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmin.html

- `.idxmax`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmax.html

In [20]:
%config InteractiveShell.ast_node_interactivity="all"

from sklearn.datasets import load_diabetes

data = load_diabetes(as_frame=True)
df = data.frame

max_age = df['age'].max()
max_age_index_1 = df[df['age'] == max_age].index
max_age_index_1

max_age_index_2 = df['age'].idxmax()
max_age_index_2

min_age_index = df['age'].idxmin()
min_age_index

Index([204, 402], dtype='int64')

204

26

---
---
## Find n smallest / largest values of a column

- `.nsmallest`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nsmallest.html

- `.nlargest`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html

In [5]:
%config InteractiveShell.ast_node_interactivity="all"

from sklearn.datasets import load_breast_cancer

data = load_breast_cancer(as_frame=True)
df = data.frame

df.nsmallest(3, 'mean radius')
df.nlargest(2, 'mean radius')

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
101,6.981,13.43,43.79,143.5,0.11700,0.07568,0.00000,0.00000,0.1930,0.07818,...,19.54,50.41,185.2,0.1584,0.1202,0.0000,0.00,0.2932,0.09382,1
539,7.691,25.44,48.34,170.4,0.08668,0.11990,0.09252,0.01364,0.2037,0.07751,...,31.89,54.49,223.6,0.1596,0.3064,0.3393,0.05,0.2790,0.10660,1
538,7.729,25.49,47.98,178.8,0.08098,0.04878,0.00000,0.00000,0.1870,0.07285,...,30.92,57.17,248.0,0.1256,0.0834,0.0000,0.00,0.3058,0.09938,1

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
212,28.11,18.47,188.5,2499.0,0.1142,0.1516,0.3201,0.1595,0.1648,0.05525,...,18.47,188.5,2499.0,0.1142,0.1516,0.3201,0.1595,0.1648,0.05525,0
461,27.42,26.27,186.9,2501.0,0.1084,0.1988,0.3635,0.1689,0.2061,0.05623,...,31.37,251.2,4254.0,0.1357,0.4256,0.6833,0.2625,0.2641,0.07427,0

---
---
## Find not equal

- `.ne`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ne.html

In [8]:
import pandas as pd

df = pd.DataFrame({'X': [0,0,0,0,0,0,0,1,2,3,4,5]})
mask = df['X'].ne(0)
df[mask]

    X
7   1
8   2
9   3
10  4
11  5

---
---
## Convert DataFrame to Markdown

- `.to_markdown`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html

In [ ]:
from sklearn.datasets import load_iris

data = load_iris(as_frame=True)
df = data.frame

print(df.to_markdown())

|     |   sepal length (cm) |   sepal width (cm) |   petal length (cm) |   petal width (cm) |   target |
|----:|--------------------:|-------------------:|--------------------:|-------------------:|---------:|
|   0 |                 5.1 |                3.5 |                 1.4 |                0.2 |        0 |
|   1 |                 4.9 |                3   |                 1.4 |                0.2 |        0 |
|   2 |                 4.7 |                3.2 |                 1.3 |                0.2 |        0 |
|   3 |                 4.6 |                3.1 |                 1.5 |                0.2 |        0 |
|   4 |                 5   |                3.6 |                 1.4 |                0.2 |        0 |
|   5 |                 5.4 |                3.9 |                 1.7 |                0.4 |        0 |
|   6 |                 4.6 |                3.4 |                 1.4 |                0.3 |        0 |
|   7 |                 5   |                3.4 |                 1.5 |                0.2 |        0 |
|   8 |                 4.4 |                2.9 |                 1.4 |                0.2 |        0 |
|   9 |                 4.9 |                3.1 |                 1.5 |                0.1 |        0 |
|  10 |                 5.4 |                3.7 |                 1.5 |                0.2 |        0 |
|  11 |                 4.8 |                3.4 |                 1.6 |                0.2 |        0 |
|  12 |                 4.8 |                3   |                 1.4 |                0.1 |        0 |
|  13 |                 4.3 |                3   |                 1.1 |                0.1 |        0 |
|  14 |                 5.8 |                4   |                 1.2 |                0.2 |        0 |
|  15 |                 5.7 |                4.4 |                 1.5 |                0.4 |        0 |
|  16 |                 5.4 |                3.9 |                 1.3 |                0.4 |        0 |
|  17 |                 5.1 |                3.5 |                 1.4 |                0.3 |        0 |
|  18 |                 5.7 |                3.8 |                 1.7 |                0.3 |        0 |
|  19 |                 5.1 |                3.8 |                 1.5 |                0.3 |        0 |
|  20 |                 5.4 |                3.4 |                 1.7 |                0.2 |        0 |
|  21 |                 5.1 |                3.7 |                 1.5 |                0.4 |        0 |
|  22 |                 4.6 |                3.6 |                 1   |                0.2 |        0 |
|  23 |                 5.1 |                3.3 |                 1.7 |                0.5 |        0 |
|  24 |                 4.8 |                3.4 |                 1.9 |                0.2 |        0 |
|  25 |                 5   |                3   |                 1.6 |                0.2 |        0 |
|  26 |                 5   |                3.4 |                 1.6 |                0.4 |        0 |
|  27 |                 5.2 |                3.5 |                 1.5 |                0.2 |        0 |
|  28 |                 5.2 |                3.4 |                 1.4 |                0.2 |        0 |
|  29 |                 4.7 |                3.2 |                 1.6 |                0.2 |        0 |
|  30 |                 4.8 |                3.1 |                 1.6 |                0.2 |        0 |
|  31 |                 5.4 |                3.4 |                 1.5 |                0.4 |        0 |
|  32 |                 5.2 |                4.1 |                 1.5 |                0.1 |        0 |
|  33 |                 5.5 |                4.2 |                 1.4 |                0.2 |        0 |
|  34 |                 4.9 |                3.1 |                 1.5 |                0.2 |        0 |
|  35 |                 5   |                3.2 |                 1.2 |                0.2 |        0 |
|  36 |                 5.5 |                3.5 |                 1.3 |                0.2 |        0 |
|  37 |                 4.9 |                3.6 |                 1.4 |                0.1 |        0 |
|  38 |                 4.4 |                3   |                 1.3 |                0.2 |        0 |
|  39 |                 5.1 |                3.4 |                 1.5 |                0.2 |        0 |
|  40 |                 5   |                3.5 |                 1.3 |                0.3 |        0 |
|  41 |                 4.5 |                2.3 |                 1.3 |                0.3 |        0 |
|  42 |                 4.4 |                3.2 |                 1.3 |                0.2 |        0 |
|  43 |                 5   |                3.5 |                 1.6 |                0.6 |        0 |
|  44 |                 5.1 |                3.8 |                 1.9 |                0.4 |        0 |
|  45 |                 4.8 |                3   |                 1.4 |                0.3 |        0 |
|  46 |                 5.1 |                3.8 |                 1.6 |                0.2 |        0 |
|  47 |                 4.6 |                3.2 |                 1.4 |                0.2 |        0 |
|  48 |                 5.3 |                3.7 |                 1.5 |                0.2 |        0 |
|  49 |                 5   |                3.3 |                 1.4 |                0.2 |        0 |
|  50 |                 7   |                3.2 |                 4.7 |                1.4 |        1 |
|  51 |                 6.4 |                3.2 |                 4.5 |                1.5 |        1 |
|  52 |                 6.9 |                3.1 |                 4.9 |                1.5 |        1 |
|  53 |                 5.5 |                2.3 |                 4   |                1.3 |        1 |
|  54 |                 6.5 |                2.8 |                 4.6 |                1.5 |        1 |
|  55 |                 5.7 |                2.8 |                 4.5 |                1.3 |        1 |
|  56 |                 6.3 |                3.3 |                 4.7 |                1.6 |        1 |
|  57 |                 4.9 |                2.4 |                 3.3 |                1   |        1 |
|  58 |                 6.6 |                2.9 |                 4.6 |                1.3 |        1 |
|  59 |                 5.2 |                2.7 |                 3.9 |                1.4 |        1 |
|  60 |                 5   |                2   |                 3.5 |                1   |        1 |
|  61 |                 5.9 |                3   |                 4.2 |                1.5 |        1 |
|  62 |                 6   |                2.2 |                 4   |                1   |        1 |
|  63 |                 6.1 |                2.9 |                 4.7 |                1.4 |        1 |
|  64 |                 5.6 |                2.9 |                 3.6 |                1.3 |        1 |
|  65 |                 6.7 |                3.1 |                 4.4 |                1.4 |        1 |
|  66 |                 5.6 |                3   |                 4.5 |                1.5 |        1 |
|  67 |                 5.8 |                2.7 |                 4.1 |                1   |        1 |
|  68 |                 6.2 |                2.2 |                 4.5 |                1.5 |        1 |
|  69 |                 5.6 |                2.5 |                 3.9 |                1.1 |        1 |
|  70 |                 5.9 |                3.2 |                 4.8 |                1.8 |        1 |
|  71 |                 6.1 |                2.8 |                 4   |                1.3 |        1 |
|  72 |                 6.3 |                2.5 |                 4.9 |                1.5 |        1 |
|  73 |                 6.1 |                2.8 |                 4.7 |                1.2 |        1 |
|  74 |                 6.4 |                2.9 |                 4.3 |                1.3 |        1 |
|  75 |                 6.6 |                3   |                 4.4 |                1.4 |        1 |
|  76 |                 6.8 |                2.8 |                 4.8 |                1.4 |        1 |
|  77 |                 6.7 |                3   |                 5   |                1.7 |        1 |
|  78 |                 6   |                2.9 |                 4.5 |                1.5 |        1 |
|  79 |                 5.7 |                2.6 |                 3.5 |                1   |        1 |
|  80 |                 5.5 |                2.4 |                 3.8 |                1.1 |        1 |
|  81 |                 5.5 |                2.4 |                 3.7 |                1   |        1 |
|  82 |                 5.8 |                2.7 |                 3.9 |                1.2 |        1 |
|  83 |                 6   |                2.7 |                 5.1 |                1.6 |        1 |
|  84 |                 5.4 |                3   |                 4.5 |                1.5 |        1 |
|  85 |                 6   |                3.4 |                 4.5 |                1.6 |        1 |
|  86 |                 6.7 |                3.1 |                 4.7 |                1.5 |        1 |
|  87 |                 6.3 |                2.3 |                 4.4 |                1.3 |        1 |
|  88 |                 5.6 |                3   |                 4.1 |                1.3 |        1 |
|  89 |                 5.5 |                2.5 |                 4   |                1.3 |        1 |
|  90 |                 5.5 |                2.6 |                 4.4 |                1.2 |        1 |
|  91 |                 6.1 |                3   |                 4.6 |                1.4 |        1 |
|  92 |                 5.8 |                2.6 |                 4   |                1.2 |        1 |
|  93 |                 5   |                2.3 |                 3.3 |                1   |        1 |
|  94 |                 5.6 |                2.7 |                 4.2 |                1.3 |        1 |
|  95 |                 5.7 |                3   |                 4.2 |                1.2 |        1 |
|  96 |                 5.7 |                2.9 |                 4.2 |                1.3 |        1 |
|  97 |                 6.2 |                2.9 |                 4.3 |                1.3 |        1 |
|  98 |                 5.1 |                2.5 |                 3   |                1.1 |        1 |
|  99 |                 5.7 |                2.8 |                 4.1 |                1.3 |        1 |
| 100 |                 6.3 |                3.3 |                 6   |                2.5 |        2 |
| 101 |                 5.8 |                2.7 |                 5.1 |                1.9 |        2 |
| 102 |                 7.1 |                3   |                 5.9 |                2.1 |        2 |
| 103 |                 6.3 |                2.9 |                 5.6 |                1.8 |        2 |
| 104 |                 6.5 |                3   |                 5.8 |                2.2 |        2 |
| 105 |                 7.6 |                3   |                 6.6 |                2.1 |        2 |
| 106 |                 4.9 |                2.5 |                 4.5 |                1.7 |        2 |
| 107 |                 7.3 |                2.9 |                 6.3 |                1.8 |        2 |
| 108 |                 6.7 |                2.5 |                 5.8 |                1.8 |        2 |
| 109 |                 7.2 |                3.6 |                 6.1 |                2.5 |        2 |
| 110 |                 6.5 |                3.2 |                 5.1 |                2   |        2 |
| 111 |                 6.4 |                2.7 |                 5.3 |                1.9 |        2 |
| 112 |                 6.8 |                3   |                 5.5 |                2.1 |        2 |
| 113 |                 5.7 |                2.5 |                 5   |                2   |        2 |
| 114 |                 5.8 |                2.8 |                 5.1 |                2.4 |        2 |
| 115 |                 6.4 |                3.2 |                 5.3 |                2.3 |        2 |
| 116 |                 6.5 |                3   |                 5.5 |                1.8 |        2 |
| 117 |                 7.7 |                3.8 |                 6.7 |                2.2 |        2 |
| 118 |                 7.7 |                2.6 |                 6.9 |                2.3 |        2 |
| 119 |                 6   |                2.2 |                 5   |                1.5 |        2 |
| 120 |                 6.9 |                3.2 |                 5.7 |                2.3 |        2 |
| 121 |                 5.6 |                2.8 |                 4.9 |                2   |        2 |
| 122 |                 7.7 |                2.8 |                 6.7 |                2   |        2 |
| 123 |                 6.3 |                2.7 |                 4.9 |                1.8 |        2 |
| 124 |                 6.7 |                3.3 |                 5.7 |                2.1 |        2 |
| 125 |                 7.2 |                3.2 |                 6   |                1.8 |        2 |
| 126 |                 6.2 |                2.8 |                 4.8 |                1.8 |        2 |
| 127 |                 6.1 |                3   |                 4.9 |                1.8 |        2 |
| 128 |                 6.4 |                2.8 |                 5.6 |                2.1 |        2 |
| 129 |                 7.2 |                3   |                 5.8 |                1.6 |        2 |
| 130 |                 7.4 |                2.8 |                 6.1 |                1.9 |        2 |
| 131 |                 7.9 |                3.8 |                 6.4 |                2   |        2 |
| 132 |                 6.4 |                2.8 |                 5.6 |                2.2 |        2 |
| 133 |                 6.3 |                2.8 |                 5.1 |                1.5 |        2 |
| 134 |                 6.1 |                2.6 |                 5.6 |                1.4 |        2 |
| 135 |                 7.7 |                3   |                 6.1 |                2.3 |        2 |
| 136 |                 6.3 |                3.4 |                 5.6 |                2.4 |        2 |
| 137 |                 6.4 |                3.1 |                 5.5 |                1.8 |        2 |
| 138 |                 6   |                3   |                 4.8 |                1.8 |        2 |
| 139 |                 6.9 |                3.1 |                 5.4 |                2.1 |        2 |
| 140 |                 6.7 |                3.1 |                 5.6 |                2.4 |        2 |
| 141 |                 6.9 |                3.1 |                 5.1 |                2.3 |        2 |
| 142 |                 5.8 |                2.7 |                 5.1 |                1.9 |        2 |
| 143 |                 6.8 |                3.2 |                 5.9 |                2.3 |        2 |
| 144 |                 6.7 |                3.3 |                 5.7 |                2.5 |        2 |
| 145 |                 6.7 |                3   |                 5.2 |                2.3 |        2 |
| 146 |                 6.3 |                2.5 |                 5   |                1.9 |        2 |
| 147 |                 6.5 |                3   |                 5.2 |                2   |        2 |
| 148 |                 6.2 |                3.4 |                 5.4 |                2.3 |        2 |
| 149 |                 5.9 |                3   |                 5.1 |                1.8 |        2 |

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

---
---
---