# **🗃️ Data Collection**

<img src="assets/data_collection_banner.jpg" style="width:95%">

---
---
---
# **🧪 Quick Sources**

---
---
## **└── Python dictionary**

In [1]:
import pandas as pd

data_dict = {
    'col1': [1, 2, 3, 4, 5],
    'col2': ['A', 'B', 'C', 'D', 'E'],
}

df = pd.DataFrame(data_dict)
df.head()

   col1 col2
0     1    A
1     2    B
2     3    C
3     4    D
4     5    E

---
---
## **└── Scikit-learn**

In [2]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing(as_frame=True)
X = data.data
y = data.target

df = pd.concat([X, y.rename('target')], axis=1)
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [3]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer(as_frame=True)
X = data.data
y = data.target

df = pd.concat([X, y.rename('target')], axis=1)
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

---
---
---
# **📁 Data Storage File Types**

- Used for storing datasets that are loaded into pandas, NumPy, Spark, etc.

| File Type              | Description                                 | When to Use                                  |
| ---------------------- | ------------------------------------------- | -------------------------------------------- |
| **`.csv`**             | Plain text, comma-separated values          | ✅ Small to medium datasets<br>✅ Easy to edit |
| **`.json`**            | Structured, hierarchical (dict-like) data   | ✅ Nested or semi-structured data             |
| **`.xlsx`**            | Excel spreadsheet                           | ✅ Business data or user-supplied files       |
| **`.parquet`**         | Columnar, compressed binary format          | ✅ Big data<br>✅ Fast I/O<br>✅ Cloud systems  |
| **`.feather`**         | Lightweight columnar format (like Parquet)  | ✅ Extremely fast in-memory read/write        |
| **`.hdf5`**            | Hierarchical binary data                    | ✅ Scientific computing, time series          |
| **`.npy` / `.npz`**    | NumPy binary formats                        | ✅ Fast model input/output                    |
| **`.pkl` / `.joblib`** | Serialized Python objects (incl. ML models) | ✅ Storing models or preprocessed data        |

---
---
## **└── CSV from local file**

- https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [4]:
import pandas as pd 

df = pd.read_csv("./data/education_inequality.csv", on_bad_lines="skip")
df.head()

,id,school_name,state,school_type,grade_level,funding_per_student_usd,avg_test_score_percent,student_teacher_ratio,percent_low_income,percent_minority,internet_access_percent,dropout_rate_percent
0,1,Bowman High School,Michigan,Private,High,9575.80,65.9,17.5,30.0,44.0,74.1,3.44
1,2,Foster High School,Michigan,Charter,Middle,16733.10,87.3,24.2,93.5,40.1,79.9,8.67
2,3,Henson High School,New York,Public,Middle,24890.74,72.8,27.0,58.1,35.8,51.1,14.75
3,4,Weaver High School,Texas,Private,Elementary,6857.49,81.5,26.2,82.7,72.0,55.5,13.45
4,5,King Elementary School,Michigan,Public,Elementary,16910.73,44.7,20.2,41.4,16.1,57.8,6.98

---
---
## **└── CSV from URL**

In [5]:
import pandas as pd 

df = pd.read_csv("https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv")
df.head()

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

---
---
## **└── JSON from local file**

In [6]:
import pandas as pd 

df = pd.read_json("./data/lung_cancer.json")
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,1,1,1,2,2,1,2,2,2,2,2,2,1,NO
1,F,55,1,2,2,1,1,2,2,2,1,1,1,2,2,NO
2,F,78,2,2,1,1,1,2,1,2,1,1,2,1,1,YES
3,M,60,2,1,1,1,2,1,2,1,1,2,1,2,2,YES
4,F,80,1,1,2,1,1,2,1,2,1,1,1,1,2,NO

---
---
## **└── JSON from URL**

In [7]:
import pandas as pd
import requests

response = requests.get("https://jsonplaceholder.typicode.com/posts")
response.raise_for_status()  # Raise error for bad responses (4xx, 5xx)
data_json = response.json()

df = pd.DataFrame(data_json)
df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

---
---
## **└── Excel from local file**

In [8]:
import pandas as pd 

df = pd.read_excel("./data/superstore_sales.xlsx", sheet_name='Orders')
df.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2015-05-12,2015-05-13,-24.0300,7,22.23,86838

---
---
## **└── Excel from URL**

In [9]:
import pandas as pd
import requests
import zipfile
import io

r = requests.get("https://www.contextures.com/SampleData.zip")
z = zipfile.ZipFile(io.BytesIO(r.content))
excel_file = z.open("SampleData.xlsx")

df = pd.read_excel(excel_file)
df.head()

   Unnamed: 0 Unnamed: 1               Unnamed: 2
0         NaN        NaN                      NaN
1         NaN        NaN                      NaN
2         NaN        NaN                      NaN
3         NaN        NaN  Online Instruction Page
4         NaN        NaN    Sample Data for Excel

---
---
## **└── Parquet from local file**

- A Parquet file is an open-source, columnar data file format designed for efficient data storage and retrieval, particularly in big data environments.
- Unlike traditional row-based formats like CSV or JSON, Parquet organizes data by columns, offering significant advantages for analytical workloads.

In [10]:
import pandas as pd 

df = pd.read_parquet("./data/titanic.parquet")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

---
---
## **└── Parquet from URL**

In [11]:
import pandas as pd

df = pd.read_parquet("https://www.timestored.com/data/sample/table.parquet")
df.head()

   one  two  three                      four                five
a -1.0  foo   True 2022-12-23 00:00:00+00:00 2022-12-23 11:43:49
b  NaN  bar  False 2021-12-23 00:00:00+00:00 2021-12-23 12:44:50
c  2.5  baz   None 2020-12-23 00:00:00+00:00 2020-12-23 13:45:51

---
---
---
# **🛢️ Database File Types**

- Actual databases or database dumps used before or during model training.

| File Type                  | Description                           | When to Use                        |
| -------------------------- | ------------------------------------- | ---------------------------------- |
| **`.db` / `.sqlite`**      | Local SQLite database                 | ✅ Lightweight DB for ML demos      |
| **`.sql`**                 | SQL dump (PostgreSQL, MySQL, etc.)    | ✅ Reconstruct database from backup |
| **No file (connected DB)** | Cloud DBs (BigQuery, Snowflake, etc.) | ✅ Real-time or big data querying   |

---
---
## **└── .db file from local file**

- `sqlite3` comes built-in with Python.
- Limited to SQLite databases only.
- Provides a low-level, direct interface to SQLite databases.
- You write raw SQL queries and manage connections/cursors yourself.
- Good for simple scripts or quick prototyping.

In [12]:
import sqlite3
import pandas as pd

db_path = "./data/bmarket.db"

with sqlite3.connect(db_path) as conn:
    query = "SELECT name FROM sqlite_master WHERE type='table';"
    tables_df = pd.read_sql(query, conn)
    
tables_df

             name
0  bank_marketing

In [13]:
import sqlite3
import pandas as pd

db_path = "./data/bmarket.db"

with sqlite3.connect(db_path) as conn:
    query = "SELECT * from bank_marketing"
    df = pd.read_sql(query, conn)

df.head()

,Client ID,Age,Occupation,Marital Status,Education Level,Credit Default,Housing Loan,Personal Loan,Contact Method,Campaign Calls,Previous Contact Days,Subscription Status
0,32885,57 years,technician,married,high.school,no,no,yes,Cell,1,999,no
1,3170,55 years,unknown,married,unknown,unknown,yes,no,telephone,2,999,no
2,32207,33 years,blue-collar,married,basic.9y,no,no,no,cellular,1,999,no
3,9404,36 years,admin.,married,high.school,no,no,no,Telephone,4,999,no
4,14021,27 years,housemaid,married,high.school,no,None,no,Cell,2,999,no

---
---
---
# **🌐 Webscraping**

---
---
## **└── HTML Table**

In [15]:
# import pandas as pd

# tables = pd.read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)")
# df = tables[1]
# df.head()

---
---
---